core/urls.py
from django.contrib import admin
from django.urls import path
import core.views
from .views import ContatoView, CreatePostView

app_name = 'core'

urlpatterns = [
    path('', core.views.index, name='index'),
    path('contato/', ContatoView.as_view(), name='contato'),
    path('post/', CreatePostView.as_view(), name='criar-post')
]

ptaDjango/urls.py
from django.contrib import admin
from django.urls import path, include
import core.views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model): 
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField('Imagem', upload_to='institute/', null=True)
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from core.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']
        labels = {
            "title": "Título",
            "text": "Conteúdo"
        }

    def save(self, commit=True):

        self.instance.author = self.initial['author']
        self.instance.save()
        return super().save()

core/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from .forms import PostForm

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse  
from django.urls import reverse_lazy
from templated_email import send_templated_mail


def index(request):
    return render(request, 'core/index.html', {'posts':Post.objects.all()})

class ContatoView(generic.TemplateView):
    template_name = 'core/contato.html'
    def post (self,request, *args, **kwargs):
        print('teste')
        nome=request.POST.get('nome')
        email=request.POST.get('email')
        telefone=request.POST.get('telefone')
        assunto=request.POST.get('assunto')
        mensagem=request.POST.get('mensagem')
        send_templated_mail(
        template_name='email',
        from_email= email,
        recipient_list=['edgarmarques123321@gmail.com'],
        context={
            'nome':nome,
            'email':email,
            'telefone':telefone,
            'assunto':assunto,
            'mensagem':mensagem
        },)
        print('teste2')
        return HttpResponseRedirect(reverse_lazy("core:contato"))

class CreatePostView(generic.CreateView):
    template_name = 'core/create-post.html'
    model = Post
    form_class = PostForm

    #   
    #   O teu erro tava nessa função:
    #   Tu tava chamando get_sucess_url e é get_success_url
    #
    # def get_sucess_url(self):
    #     return reverse_lazy('core:index')

    def get_success_url(self):
        return reverse_lazy('core:index')

    
    def get_initial(self):
        return {'author': self.request.user}
        
# Create your views here.admin/core/posts/

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
    
<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/footer.css' %}">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% block meta %}
  {% endblock %}
  <title>Blog Django | CITi - PTA</title>
    {% block css %}
    <link rel="stylesheet"  href="{% static 'css/style.css' %}" >

    {% endblock %}
</head>
<body>
    {% include "includes/navbar.html" %}
    
    {% block body %}
        
    {% endblock %}

    {% include 'includes/footer.html' %}

    {% block script %}
    {% endblock %}
</body>


</html>

templates/core/contato.html
{% extends 'base.html' %} 
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block body %}
<section class="contato-section" id="contato">
    <h2 class="contato-title">Contato</h2>
    <div class="contato-container">
      <div class="contato-left-info">
          <h4 class="contato-left-info-title">TELEFONE</h4>
          <p class="contato-left-info-content">(XX) X XXXX-XXXX</p>
          <h4 class="contato-left-info-title">EMAIL</h4>
          <div class="contato-left-mail">
              <a href="mailto: exemplo@hotmail.com" class="contato-left-info-content">exemplo@hotmail.com</a>
              <div class="contato-left-email-underline"></div>
          </div>
      </div>
      <form class="contato-form"  method="POST" autocomplete="off">
        {% csrf_token %}
          <div class="contato-line">
            <label for="Nome" class="contato-label">Nome:</label>
              <input class="contato-text-input" type="text" name="nome" placeholder="Nome Completo" required="required">
              <label for="Email" class="contato-label">Email:</label>
              <input class="contato-text-input" type="email" name="email" placeholder="Email" required="required">
          </div>
          <div class="contato-line">
              <label for="Assunto" class="contato-label">Assunto:</label>
              <input class="contato-text-input" type="text" name="assunto" placeholder="Assunto" required="required">
              <label for="Telefone" class="contato-label">Telefone:</label>
              <input class="contato-text-input" type="telefone" name="telefone" placeholder="Telefone" required="required">
          </div>
          <label for="Mensagem" class="contato-label" id="contato-mensagem-label">Mensagem:</label>
          <textarea class="contato-textarea" name="mensagem" placeholder="Em que posso lhe ajudar?" required="required"> </textarea>
          <p class="contato-feedback"></p>
          <input class="contato-btn" type="submit" value="ENVIAR">
      </form>
    </div>
</section>
{% endblock %}

{% block script %}
{% endblock %}

templates/core/create-post.html
{% extends 'base.html' %} 
{% load static %}
{% load widget_tweaks %}


{% block css %}
  <link rel="stylesheet" href="{% static 'css/create-post.css' %}">
{% endblock %}

{% block body %}
<form class="contato-form"  method="POST" autocomplete="off">
    {% csrf_token %}
    <h1>Criar uma Postagem</h1>
    <p>
        {{ form.title.label_tag }}
        {% render_field form.title class="form-field" placeholder="Título da postagem"|attr='required:True' %}
    </p>
    <p>
        {{ form.text.label_tag }}
        {% render_field form.text class="form-field" placeholder="Conteúdo da postagem"|attr='required:True' %}
    </p>
    <input class="contato-btn" type="submit" value="ENVIAR">
</form>
{% endblock %}

{% block script %}
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <main>
        <h2>Postagens</h2>
        {% for post in posts %}
        {% if post.image %}
            <img src="{{ post.image.url }}">
            {% endif %}
            <article class="post">
                <h3>
                    {{ post.title }}
                </h3>
                <p class="post-text">
                    {{ post.text }}
                </p>
                <div class="post-info">
                    <span>Criado por: {{ post.author }}</span>
                    <span>{{ post.created_date }}</span>
                </div>
            </article>    
        {% endfor %}
    </main>

{% endblock %}

templates/includes/footer.html
{% load staticfiles %}
<footer class="footer">
    <div class="footer-container">
        <div class="footer-telefone">
            <span>Tel:(81) 997748348 </span>
        </div>
       
        <div class="footer-email">
            <a class="footer-email-link" href="mailto:{{ footer.Email }}">contato@citi.org.br</a>  
        </div>
        <div class="footer-made">
            <p>Made with <i class="fas fa-code"></i> and <i class="fas fa-heart"></i> by </p>
            <a href="http://citi.org.br/" rel="nofollow, external, noopener" target="_blank"> <img src="{% static 'images/citi.svg' %}" alt="Logo do CITi" class="funcionamento-ant"></a>
        </div>
    </div>
</footer>
{% block script %}


{% endblock %}

templates/includes/navbar.html
{% load static%}

<header>
    <div>
        <a href="{% url 'core:index'%}">
            <img src="{% static 'images/citi.svg'%}" alt="logo" id="logo-citi">
        </a>
        <a class="navbar-titulo" href="{% url 'core:index' %}">Blog PTA</a>
        <a class="navbar-titulo" href="{% url 'core:contato' %}">Contato</a>
        <a class="navbar-titulo" href="{% url 'core:criar-post' %}">Postar</a>
    </div>
</header>